#include "EffectEngine.h"
#include <android/log.h>
#include "EffectShaders.h"
namespace ah_fx {
static const char* TAG="AhEffects";
static GLuint compileShader(GLenum type,const char*src){GLuint s=glCreateShader(type);glShaderSource(s,1,&src,nullptr);glCompileShader(s);GLint ok=0;glGetShaderiv(s,GL_COMPILE_STATUS,&ok);if(!ok){char log[1024]={0};glGetShaderInfoLog(s,sizeof(log)-1,nullptr,log);__android_log_print(ANDROID_LOG_ERROR,TAG,"shader compile failed: %s",log);glDeleteShader(s);return 0;}return s;}
EffectEngine::Prog* EffectEngine::program(int key){auto it=progs_.find(key);if(it!=progs_.end())return &it->second;if(failedKeys_.count(key))return nullptr;const char*fsSrc=fragmentSource(key);GLuint vs=compileShader(GL_VERTEX_SHADER,vertexSource()),fs=fsSrc?compileShader(GL_FRAGMENT_SHADER,fsSrc):0;GLuint id=0;if(vs&&fs){id=glCreateProgram();glAttachShader(id,vs);glAttachShader(id,fs);glLinkProgram(id);GLint ok=0;glGetProgramiv(id,GL_LINK_STATUS,&ok);if(!ok){glDeleteProgram(id);id=0;}}if(vs)glDeleteShader(vs);if(fs)glDeleteShader(fs);if(!id){failedKeys_[key]=true;failed_++;__android_log_print(ANDROID_LOG_ERROR,TAG,"effect shader %d unavailable",key);return nullptr;}Prog p;p.id=id;p.uTex=glGetUniformLocation(id,"uTex");p.uSrc=glGetUniformLocation(id,"uSrc");p.uRes=glGetUniformLocation(id,"uRes");p.uTime=glGetUniformLocation(id,"uTime");p.uInt=glGetUniformLocation(id,"uIntensity");p.uP=glGetUniformLocation(id,"uP");p.uDir=glGetUniformLocation(id,"uDir");return &(progs_[key]=p);}
bool EffectEngine::init(){if(initialized_)return true;glGenVertexArrays(1,&vao_);if(!vao_)return false;initialized_=true;bool ok=program(KEY_COPY)!=nullptr;for(int id=1;id<FX_COUNT;id++)program(id);program(KEY_BRIGHT);program(KEY_COMPOSITE);if(!ok){release();return false;}return true;}
bool EffectEngine::ensureTargets(int w,int h){if(tw_==w&&th_==h&&t_[0].fbo)return true;destroyTargets();tw_=w;th_=h;for(auto&i:t_){glGenTextures(1,&i.tex);glBindTexture(GL_TEXTURE_2D,i.tex);glTexImage2D(GL_TEXTURE_2D,0,GL_RGBA,w,h,0,GL_RGBA,GL_UNSIGNED_BYTE,nullptr);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_LINEAR);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_LINEAR);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,GL_CLAMP_TO_EDGE);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,GL_CLAMP_TO_EDGE);glGenFramebuffers(1,&i.fbo);glBindFramebuffer(GL_FRAMEBUFFER,i.fbo);glFramebufferTexture2D(GL_FRAMEBUFFER,GL_COLOR_ATTACHMENT0,GL_TEXTURE_2D,i.tex,0);if(glCheckFramebufferStatus(GL_FRAMEBUFFER)!=GL_FRAMEBUFFER_COMPLETE)return false;}glBindFramebuffer(GL_FRAMEBUFFER,0);glBindTexture(GL_TEXTURE_2D,0);return true;}
void EffectEngine::destroyTargets(){for(auto&i:t_){if(i.fbo)glDeleteFramebuffers(1,&i.fbo);if(i.tex)glDeleteTextures(1,&i.tex);i=Target();}tw_=th_=0;}
void EffectEngine::pass(int key,GLuint tex,GLuint src,GLuint dstFbo,int w,int h,float timeSec,float intensity,const float*p,float dx,float dy){Prog*pr=program(key);if(!pr){pr=program(KEY_COPY);intensity=1;}if(!pr)return;glBindFramebuffer(GL_FRAMEBUFFER,dstFbo);glViewport(0,0,w,h);glDisable(GL_BLEND);glUseProgram(pr->id);glActiveTexture(GL_TEXTURE0);glBindTexture(GL_TEXTURE_2D,tex);glActiveTexture(GL_TEXTURE1);glBindTexture(GL_TEXTURE_2D,src);glUniform1i(pr->uTex,0);glUniform1i(pr->uSrc,1);glUniform2f(pr->uRes,(float)w,(float)h);glUniform1f(pr->uTime,timeSec);glUniform1f(pr->uInt,intensity);float z[kMaxParams]={0};glUniform1fv(pr->uP,kMaxParams,p?p:z);glUniform2f(pr->uDir,dx,dy);glDrawArrays(GL_TRIANGLE_STRIP,0,4);}
void EffectEngine::runEffect(const Resolved&e,GLuint cur,GLuint dstFbo,int w,int h,float t){switch(e.id){case FX_GAUSSIAN_BLUR:pass(FX_GAUSSIAN_BLUR,cur,cur,t_[2].fbo,w,h,t,1,e.p,1,0);pass(FX_GAUSSIAN_BLUR,t_[2].tex,cur,dstFbo,w,h,t,e.intensity,e.p,0,1);break;case FX_BLOOM:{float bright[kMaxParams]={e.p[0]};float blur[kMaxParams]={e.p[1]};pass(KEY_BRIGHT,cur,cur,t_[2].fbo,w,h,t,1,bright,0,0);pass(FX_GAUSSIAN_BLUR,t_[2].tex,t_[2].tex,t_[3].fbo,w,h,t,1,blur,1,0);pass(FX_GAUSSIAN_BLUR,t_[3].tex,t_[3].tex,t_[2].fbo,w,h,t,1,blur,0,1);pass(KEY_COMPOSITE,t_[2].tex,cur,dstFbo,w,h,t,e.intensity,e.p,0,0);break;}default:pass(e.id,cur,cur,dstFbo,w,h,t,e.intensity,e.p,0,0);}}
int EffectEngine::render(GLuint inputTex,int w,int h,float timeMs,const std::vector<Instance>&chain,GLuint outputFbo){if(!initialized_||!inputTex||w<=0||h<=0||w>16384||h>16384)return -1;std::vector<Resolved>active;for(const auto&in:chain){Resolved r;if(resolveInstance(in,timeMs,r))active.push_back(r);}glDisable(GL_DEPTH_TEST);glDisable(GL_CULL_FACE);glDisable(GL_SCISSOR_TEST);glBindVertexArray(vao_);int applied=0;if(active.empty())pass(KEY_COPY,inputTex,inputTex,outputFbo,w,h,0,1,nullptr,0,0);else if(!ensureTargets(w,h)){glBindVertexArray(0);return -1;}else{GLuint cur=inputTex;int pp=0;for(size_t i=0;i<active.size();i++){bool last=i+1==active.size();GLuint dst=last?outputFbo:t_[pp].fbo;runEffect(active[i],cur,dst,w,h,(timeMs-active[i].startMs)/1000.f);cur=t_[pp].tex;pp^=1;applied++;}}glBindVertexArray(0);glUseProgram(0);glActiveTexture(GL_TEXTURE1);glBindTexture(GL_TEXTURE_2D,0);glActiveTexture(GL_TEXTURE0);glBindTexture(GL_TEXTURE_2D,0);glBindFramebuffer(GL_FRAMEBUFFER,0);return applied;}
void EffectEngine::onContextLost(){initialized_=false;vao_=0;progs_.clear();failedKeys_.clear();for(auto&i:t_)i=Target();tw_=th_=0;}
void EffectEngine::release(){if(!initialized_&&!vao_)return;destroyTargets();for(auto&kv:progs_)if(kv.second.id)glDeleteProgram(kv.second.id);progs_.clear();if(vao_)glDeleteVertexArrays(1,&vao_);vao_=0;initialized_=false;}
}